/**
 * @file enums.ts
 * @description Layer 03 确定性量化与博弈引擎枚举定义
 */

export enum Layer03OpId {
  CLEAN_CONTEXT = 'QUANT_03_CLEAN_CONTEXT',
  MOMENTUM_ANALYSIS = 'QUANT_03_MOMENTUM_ANALYSIS',
  POISSON_FORWARD_MODEL = 'QUANT_03_POISSON_FORWARD_MODEL',
  DEVIG_CALCULATION = 'QUANT_03_DEVIG_CALCULATION',
  ORCHESTRATE_QUANT = 'QUANT_03_ORCHESTRATE_QUANT'
}

export enum Layer03FeatureId {
  H2H_DECAY = 'H2H_DECAY',
  RECENT_FORM_HOMOMORPHISM = 'RECENT_FORM_HOMOMORPHISM',
  LINEUP_IMPACT_SCORE = 'LINEUP_IMPACT_SCORE',
  MOTIVATION_URGENCY_INDEX = 'MOTIVATION_URGENCY_INDEX',
  GOAL_TIMING_VALIDITY = 'GOAL_TIMING_VALIDITY',
  MOMENTUM_SLOPE_5M = 'MOMENTUM_SLOPE_5M',
  MOMENTUM_SLOPE_10M = 'MOMENTUM_SLOPE_10M',
  MOMENTUM_SLOPE_15M = 'MOMENTUM_SLOPE_15M',
  MOMENTUM_INTEGRAL_5M = 'MOMENTUM_INTEGRAL_5M',
  MOMENTUM_INTEGRAL_15M = 'MOMENTUM_INTEGRAL_15M',
  XT_PROXY_THREAT = 'XT_PROXY_THREAT',
  BARREN_DOMINANCE = 'BARREN_DOMINANCE',
  LETHAL_COUNTER = 'LETHAL_COUNTER',
  RED_CARD_PENALTY = 'RED_CARD_PENALTY',
  POISSON_LAMBDA_HOME_REST = 'POISSON_LAMBDA_HOME_REST',
  POISSON_LAMBDA_AWAY_REST = 'POISSON_LAMBDA_AWAY_REST',
  REST_SCORE_MATRIX = 'REST_SCORE_MATRIX',
  SHIN_DEVIG_FAIR_PROB = 'SHIN_DEVIG_FAIR_PROB',
  SPREAD_MAIN_EV = 'SPREAD_MAIN_EV',
  TOTAL_MAIN_EV = 'TOTAL_MAIN_EV',
  LINE_DISPERSION_VARIANCE = 'LINE_DISPERSION_VARIANCE',
  BATTLEFIELD_DOMINANCE_INDEX = 'BATTLEFIELD_DOMINANCE_INDEX',
  GOAL_PHASE_ALERT = 'GOAL_PHASE_ALERT'
}

export enum MarketType {
  FULL_H2H = 'full_h2h',
  FULL_SPREAD_MAIN = 'full_spread_main',
  FULL_SPREAD_SUBS = 'full_spread_subs',
  FULL_TOTAL_MAIN = 'full_total_main',
  FULL_TOTAL_SUBS = 'full_total_subs',
  HALF_H2H = 'half_h2h',
  HALF_SPREAD_MAIN = 'half_spread_main',
  HALF_TOTAL_MAIN = 'half_total_main'
}

export enum DevigMethod {
  MULTIPLICATIVE = 'MULTIPLICATIVE',
  SHIN = 'SHIN',
  POWER = 'POWER'
}

export enum PoissonDecayCurve {
  LINEAR_UNIFORM = 'LINEAR_UNIFORM',
  NON_LINEAR_POWER = 'NON_LINEAR_POWER',
  LATE_GAME_ACCELERATION = 'LATE_GAME_ACCELERATION'
}

export enum MomentumTrend {
  SURGING_HOME = 'SURGING_HOME',
  SURGING_AWAY = 'SURGING_AWAY',
  STALEMATE = 'STALEMATE',
  HOME_SIEGE = 'HOME_SIEGE',
  AWAY_SIEGE = 'AWAY_SIEGE',
  VOLATILE_TRANSITION = 'VOLATILE_TRANSITION'
}

export enum BookmakerPosture {
  NEUTRAL_BALANCED = 'NEUTRAL_BALANCED',
  TRAP_HIGH_ODDS = 'TRAP_HIGH_ODDS',
  INSTITUTIONAL_DEFENSE = 'INSTITUTIONAL_DEFENSE',
  DISPERSED_UNCERTAIN = 'DISPERSED_UNCERTAIN'
}

export enum GoalPhaseAlert {
  NONE = 'NONE',
  IMMINENT_GOAL = 'IMMINENT_GOAL',
  DEADLOCK_STALEMATE = 'DEADLOCK_STALEMATE',
  LOW_INTENSITY_GARBAGE_TIME = 'LOW_INTENSITY_GARBAGE_TIME'
}

export enum DataDeficitSeverity {
  L0_FATAL = 'L0_FATAL',
  L1_CORE_DEFICIT = 'L1_CORE_DEFICIT',
  L2_AUXILIARY_DEFICIT = 'L2_AUXILIARY_DEFICIT'
}

export enum L0MissingReason {
  MINUTE_UNDEFINED = 'MINUTE_UNDEFINED',
  UNVERIFIED_SCORE = 'UNVERIFIED_SCORE',
  TARGET_MARKET_MISSING = 'TARGET_MARKET_MISSING',
  ODDS_INVALID = 'ODDS_INVALID'
}

export enum QuantAlert {
  L0_FATAL_DATA_MISSING = 'L0_FATAL_DATA_MISSING',
  MOMENTUM_DATA_DEFICIT = 'MOMENTUM_DATA_DEFICIT',
  BARREN_DOMINANCE_WARNING = 'BARREN_DOMINANCE_WARNING',
  LETHAL_COUNTER_WARNING = 'LETHAL_COUNTER_WARNING',
  RED_CARD_TACTICAL_COLLAPSE = 'RED_CARD_TACTICAL_COLLAPSE',
  TRAP_HIGH_ODDS_WARNING = 'TRAP_HIGH_ODDS_WARNING',
  HIGH_LINE_DISPERSION = 'HIGH_LINE_DISPERSION'
}
