/**
 * @file enums.ts
 * @description Layer 03 确定性量化与博弈引擎枚举定义
 */

export enum Layer03OpId {
  CLEAN_CONTEXT = 'QUANT_03_CLEAN_CONTEXT',
  PREMATCH_PRIOR_SYNTHESIS = 'QUANT_03_PREMATCH_PRIOR_SYNTHESIS',
  MARKET_DIVERGENCE_CALIBRATION = 'QUANT_03_MARKET_DIVERGENCE_CALIBRATION',
  MOMENTUM_ANALYSIS = 'QUANT_03_MOMENTUM_ANALYSIS',
  POISSON_FORWARD_MODEL = 'QUANT_03_POISSON_FORWARD_MODEL',
  DEVIG_CALCULATION = 'QUANT_03_DEVIG_CALCULATION',
  CALCULATE_DEVIG_EV = 'QUANT_03_CALCULATE_DEVIG_EV',
  ORCHESTRATE_QUANT = 'QUANT_03_ORCHESTRATE_QUANT'
}

export enum Layer03FeatureId {
  H2H_DECAY = 'H2H_DECAY',
  RECENT_FORM_HOMOMORPHISM = 'RECENT_FORM_HOMOMORPHISM',
  LINEUP_IMPACT_SCORE = 'LINEUP_IMPACT_SCORE',
  MOTIVATION_URGENCY_INDEX = 'MOTIVATION_URGENCY_INDEX',
  GOAL_TIMING_VALIDITY = 'GOAL_TIMING_VALIDITY',
  PREMATCH_THEORY_PRIOR = 'PREMATCH_THEORY_PRIOR',
  MARKET_DIVERGENCE_CALIBRATION = 'MARKET_DIVERGENCE_CALIBRATION',
  MOMENTUM_SLOPE_5M = 'MOMENTUM_SLOPE_5M',
  MOMENTUM_SLOPE_10M = 'MOMENTUM_SLOPE_10M',
  MOMENTUM_SLOPE_15M = 'MOMENTUM_SLOPE_15M',
  MOMENTUM_INTEGRAL_5M = 'MOMENTUM_INTEGRAL_5M',
  MOMENTUM_INTEGRAL_15M = 'MOMENTUM_INTEGRAL_15M',
  XT_PROXY_THREAT = 'XT_PROXY_THREAT',
  BARREN_DOMINANCE = 'BARREN_DOMINANCE',
  LETHAL_COUNTER = 'LETHAL_COUNTER',
  RED_CARD_PENALTY = 'RED_CARD_PENALTY',
  POISSON_LAMBDA_HOME_REST = 'POISSON_LAMBDA_HOME_REST',
  POISSON_LAMBDA_AWAY_REST = 'POISSON_LAMBDA_AWAY_REST',
  REST_SCORE_MATRIX = 'REST_SCORE_MATRIX',
  SHIN_DEVIG_FAIR_PROB = 'SHIN_DEVIG_FAIR_PROB',
  SPREAD_MAIN_EV = 'SPREAD_MAIN_EV',
  TOTAL_MAIN_EV = 'TOTAL_MAIN_EV',
  LINE_DISPERSION_VARIANCE = 'LINE_DISPERSION_VARIANCE',
  BATTLEFIELD_DOMINANCE_INDEX = 'BATTLEFIELD_DOMINANCE_INDEX',
  GOAL_PHASE_ALERT = 'GOAL_PHASE_ALERT'
}

export enum MarketType {
  FULL_H2H = 'full_h2h',
  FULL_SPREAD_MAIN = 'full_spread_main',
  FULL_SPREAD_SUBS = 'full_spread_subs',
  FULL_TOTAL_MAIN = 'full_total_main',
  FULL_TOTAL_SUBS = 'full_total_subs',
  HALF_H2H = 'half_h2h',
  HALF_SPREAD_MAIN = 'half_spread_main',
  HALF_TOTAL_MAIN = 'half_total_main',
  MONEYLINE_1X2 = 'MONEYLINE_1X2',
  SPREAD_ASIAN = 'SPREAD_ASIAN',
  TOTAL_GOALS = 'TOTAL_GOALS'
}

export enum DevigMethod {
  MULTIPLICATIVE = 'MULTIPLICATIVE',
  SHIN = 'SHIN',
  POWER = 'POWER'
}

export enum PoissonDecayCurve {
  LINEAR_UNIFORM = 'LINEAR_UNIFORM',
  NON_LINEAR_POWER = 'NON_LINEAR_POWER',
  LATE_GAME_ACCELERATION = 'LATE_GAME_ACCELERATION',
  ACCELERATED_LATE = 'ACCELERATED_LATE',
  DESPERATION_BURST = 'DESPERATION_BURST',
  DECELERATED_SLOWDOWN = 'DECELERATED_SLOWDOWN'
}

export enum MomentumTrend {
  SURGING_HOME = 'SURGING_HOME',
  SURGING_AWAY = 'SURGING_AWAY',
  STALEMATE = 'STALEMATE',
  HOME_SIEGE = 'HOME_SIEGE',
  AWAY_SIEGE = 'AWAY_SIEGE',
  VOLATILE_TRANSITION = 'VOLATILE_TRANSITION'
}

export enum BookmakerPosture {
  NEUTRAL_BALANCED = 'NEUTRAL_BALANCED',
  TRAP_HIGH_ODDS = 'TRAP_HIGH_ODDS',
  INSTITUTIONAL_DEFENSE = 'INSTITUTIONAL_DEFENSE',
  HEAVY_DEFENSIVE = 'HEAVY_DEFENSIVE',
  BALANCED_NEUTRAL = 'BALANCED_NEUTRAL',
  DISPERSED_UNCERTAIN = 'DISPERSED_UNCERTAIN'
}

export enum GoalPhaseAlert {
  NONE = 'NONE',
  IMMINENT_GOAL = 'IMMINENT_GOAL',
  DEADLOCK_STALEMATE = 'DEADLOCK_STALEMATE',
  LOW_INTENSITY_GARBAGE_TIME = 'LOW_INTENSITY_GARBAGE_TIME'
}

export enum DataDeficitSeverity {
  L0_FATAL = 'L0_FATAL',
  L1_CORE_DEFICIT = 'L1_CORE_DEFICIT',
  L2_AUXILIARY_DEFICIT = 'L2_AUXILIARY_DEFICIT'
}

export enum L0MissingReason {
  MINUTE_UNDEFINED = 'MINUTE_UNDEFINED',
  UNVERIFIED_SCORE = 'UNVERIFIED_SCORE',
  TARGET_MARKET_MISSING = 'TARGET_MARKET_MISSING',
  ODDS_INVALID = 'ODDS_INVALID'
}

export enum QuantAlert {
  L0_FATAL_DATA_MISSING = 'L0_FATAL_DATA_MISSING',
  MOMENTUM_DATA_DEFICIT = 'MOMENTUM_DATA_DEFICIT',
  TECHNICAL_METRICS_DEFICIT = 'TECHNICAL_METRICS_DEFICIT',
  BARREN_DOMINANCE_WARNING = 'BARREN_DOMINANCE_WARNING',
  LETHAL_COUNTER_WARNING = 'LETHAL_COUNTER_WARNING',
  RED_CARD_TACTICAL_COLLAPSE = 'RED_CARD_TACTICAL_COLLAPSE',
  TRAP_HIGH_ODDS_WARNING = 'TRAP_HIGH_ODDS_WARNING',
  HIGH_LINE_DISPERSION = 'HIGH_LINE_DISPERSION',
  GOAL_CLIMAX_TRIGGERED = 'GOAL_CLIMAX_TRIGGERED',
  COLLAPSING_PANIC_WARNING = 'COLLAPSING_PANIC_WARNING'
}

export enum EventPressureConversionType {
  LETHAL_SIEGE = 'LETHAL_SIEGE',
  BARREN_DOMINANCE = 'BARREN_DOMINANCE',
  CLINICAL_COUNTER = 'CLINICAL_COUNTER',
  BALANCED_CONTEST = 'BALANCED_CONTEST',
  LOW_ENGAGEMENT = 'LOW_ENGAGEMENT'
}

export enum TacticalRegimeType {
  CRUSHING_EXPANSION = 'CRUSHING_EXPANSION',
  LEADING_CONSOLIDATION = 'LEADING_CONSOLIDATION',
  GAME_CONTROL_DECELERATION = 'GAME_CONTROL_DECELERATION',
  ELASTIC_COUNTER = 'ELASTIC_COUNTER',
  VULNERABLE_OVEREXTENSION = 'VULNERABLE_OVEREXTENSION',
  ORDERED_CHASE = 'ORDERED_CHASE',
  DESPERATION_ASSAULT = 'DESPERATION_ASSAULT',
  COLLAPSING_PANIC = 'COLLAPSING_PANIC',
  RED_CARD_RESILIENCE = 'RED_CARD_RESILIENCE',
  RED_CARD_COLLAPSE = 'RED_CARD_COLLAPSE',
  NEUTRAL_EQUILIBRIUM = 'NEUTRAL_EQUILIBRIUM'
}

export enum GoalClimaxLevel {
  EXTREME_IMMINENT = 'EXTREME_IMMINENT',
  HIGH_PRESSURE = 'HIGH_PRESSURE',
  MODERATE_BUILDUP = 'MODERATE_BUILDUP',
  DORMANT = 'DORMANT'
}

export enum MarketStanceType {
  CONSENSUS_ALIGNED = 'CONSENSUS_ALIGNED',
  INSTITUTIONAL_DEFENSE = 'INSTITUTIONAL_DEFENSE',
  TRAP_INDUCEMENT = 'TRAP_INDUCEMENT',
  MARKET_DATA_MISSING = 'MARKET_DATA_MISSING'
}

