export enum RecommendationGrade {
  A_GRADE = 'A_GRADE',
  B_GRADE = 'B_GRADE',
  C_GRADE = 'C_GRADE',
  WATCH = 'WATCH',
  RESEARCH = 'RESEARCH',
  REJECTED = 'REJECTED'
}

export enum TrapDetectionResult {
  SAFE_VALUE = 'SAFE_VALUE',
  POTENTIAL_TRAP = 'POTENTIAL_TRAP',
  CONFIRMED_TRAP = 'CONFIRMED_TRAP',
  UNCERTAIN = 'UNCERTAIN'
}

export enum TacticalRegimeEvaluation {
  GENUINE_DOMINANCE = 'GENUINE_DOMINANCE',
  BARREN_DOMINANCE = 'BARREN_DOMINANCE',
  RECIPROCAL_CHAOS = 'RECIPROCAL_CHAOS',
  TACTICAL_STALEMATE = 'TACTICAL_STALEMATE'
}
